### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by ghost** [CacheBrowser/cachebrowser#1]
Hello, it appears that none of the links on this page have attached URLs. Please advise, thank you.

http://cachebrowser.info/#/download

**Comment by d668** [comment]
+1

**Comment by tiye** [comment]
![image](https://cloud.githubusercontent.com/assets/449224/11324390/6afe423e-916b-11e5-8578-529649edcb43.png)

**Comment by Ged0** [comment]
I can't download,neither

**Comment by ha-D** [comment]
The download links have been fixed, sorry for the problem.
