### ISSUE TITLE
Bootstrapper implementation providing geographically good edge servers

### ISSUE THREAD

**Issue by ghost** [CacheBrowser/cachebrowser#12]
Some Bootstrapper implementations would only point a site to the same edge server, which may overload that edge server.

**Comment by ha-D** [comment]
True, though it should be fairly easy to avoid overloading by keeping a large number of edge servers and providing different users with different ones. 

A less serious but more difficult problem would be Bootstrapper implementations which provide geographically good edge servers to the users. It would be nice to achieve this without having to reimplement complex CDN mapping logic.
