### ISSUE TITLE
python setup.py install doesn't work

### ISSUE THREAD

**Issue by d668** [CacheBrowser/cachebrowser#3]
C:\Users\xxx\Desktop\cachebrowser-master>python setup.py install
  File "setup.py", line 72
    os.chmod(chromeexec, 0755)
                            ^
SyntaxError: invalid token

**Comment by d668** [comment]
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32

**Comment by svnpenn** [comment]
"doesn't work" is a terrible title. You should edit it to something that is actually constructive, like "SyntaxError: invalid token"

**Comment by d668** [comment]
doesn't work is a perfect title for this whole "suite"

**Comment by ha-D** [comment]
Thanks, the installation error has been fixed.

> doesn't work is a perfect title for this whole "suite"

CacheBrowser is under development and not yet fully functional, I apologize for the instabilities.
